CREATE PROCEDURE [dbo].[sp_InsertKYCRecord] 
    @AcType NVARCHAR(50), 
    @CustType NVARCHAR(50), 
    @Branch NVARCHAR(100), 
    @AppDate DATE, 
    @Email NVARCHAR(150), 
    @EmailOTP NVARCHAR(10), 
    @Mobile NVARCHAR(15), 
    @AltMobile NVARCHAR(15), 
    @AadhaarMobileOTP NVARCHAR(10), 
    @AadhaarNum NVARCHAR(20), 
    @AadhaarOTP NVARCHAR(10), 
    @AadhaarName NVARCHAR(100), 
    @AadhaarDOB DATE, 
    @Gender NVARCHAR(20), 
    @FullName NVARCHAR(100), 
    @FatherName NVARCHAR(100), 
    @MotherName NVARCHAR(100), 
    @Spouse NVARCHAR(100), 
    @Marital NVARCHAR(50), 
    @Nat NVARCHAR(50), 
    @Rel NVARCHAR(50), 
    @ResStatus NVARCHAR(50), 
    @PlaceOfBirth NVARCHAR(100), 
    @CountryOfBirth NVARCHAR(100), 
    @Street NVARCHAR(250), 
    @Locality NVARCHAR(150), 
    @Town NVARCHAR(150), 
    @PO NVARCHAR(100), 
    @City NVARCHAR(100), 
    @State NVARCHAR(100), 
    @Country NVARCHAR(100), 
    @Pin NVARCHAR(10), 
    @AddrType NVARCHAR(50), 
    @IsSame NVARCHAR(5), 
    @PermAddr NVARCHAR(500), 
    @Occ NVARCHAR(50), 
    @EmpName NVARCHAR(150), 
    @BusNature NVARCHAR(150), 
    @Role NVARCHAR(100), 
    @Income NVARCHAR(100), 
    @Funds NVARCHAR(100), 
    @PAN NVARCHAR(20), 
    @PANName NVARCHAR(100), 
    @DLNum NVARCHAR(30), 
    @DLDOB DATE, 
    @DLName NVARCHAR(100), 
    @AadhaarPath NVARCHAR(500), 
    @PANPath NVARCHAR(500), 
    @DLPath NVARCHAR(500), 
    @AddrPath NVARCHAR(500), 
    @SignPath NVARCHAR(500) 
AS 
BEGIN 
    SET NOCOUNT ON; 
    INSERT INTO [dbo].[KYCDetails] ( 
        [AccountType], [CustomerType], [PreferredBranch], [ApplicationDate], [Email], [EmailOTP], [MobileNumber], 
        [AlternateMobileNumber], [AadhaarMobileOTP], [AadhaarNumber], [AadhaarOTP], [AadhaarName], [AadhaarDOB], [Gender], 
        [FullLegalName], [FatherName], [MotherName], [SpouseGuardianName], [MaritalStatus], [Nationality], [Religion], 
        [ResidentialStatus], [PlaceOfBirth], [CountryOfBirth], [StreetHouseLandmark], [AreaLocality], [LocationVillageTown], 
        [PostOffice], [CityDistrict], [State], [Country], [Pincode], [TypeOfAddress], [IsPermanentAddressSame], [PermanentAddress], 
        [OccupationType], [EmployerName], [NatureOfBusiness], [Designation], [AnnualIncomeRange], [SourceOfFunds], 
        [PANNumber], [PANHolderName], [DrivingLicenceNumber], [DrivingLicenceDOB], [DrivingLicenceName], 
        [AadhaarCardPath], [PANCardPath], [PassportDLPath], [AddressProofPath], [SignatureScanPath] 
    ) VALUES ( 
        @AcType, @CustType, @Branch, @AppDate, @Email, @EmailOTP, @Mobile, 
        @AltMobile, @AadhaarMobileOTP, @AadhaarNum, @AadhaarOTP, @AadhaarName, @AadhaarDOB, @Gender, 
        @FullName, @FatherName, @MotherName, @Spouse, @Marital, @Nat, @Rel, 
        @ResStatus, @PlaceOfBirth, @CountryOfBirth, @Street, @Locality, @Town, 
        @PO, @City, @State, @Country, @Pin, @AddrType, @IsSame, @PermAddr, 
        @Occ, @EmpName, @BusNature, @Role, @Income, @Funds, 
        @PAN, @PANName, @DLNum, @DLDOB, @DLName, 
        @AadhaarPath, @PANPath, @DLPath, @AddrPath, @SignPath 
    ); 
    SELECT SCOPE_IDENTITY() AS [NewRecordId]; 
END
