CREATE PROCEDURE [dbo].[sp_UpdateKYCRecord] 
    @Id INT, 
    @AcType NVARCHAR(50), 
    @CustType NVARCHAR(50), 
    @Branch NVARCHAR(100), 
    @Email NVARCHAR(150), 
    @EmailOTP NVARCHAR(10), 
    @Mobile NVARCHAR(15), 
    @AltMobile NVARCHAR(15), 
    @AadhaarMobileOTP NVARCHAR(10), 
    @AadhaarNum NVARCHAR(20), 
    @AadhaarOTP NVARCHAR(10), 
    @AadhaarName NVARCHAR(100), 
    @AadhaarDOB DATE, 
    @Gender NVARCHAR(20), 
    @FullName NVARCHAR(100), 
    @FatherName NVARCHAR(100), 
    @MotherName NVARCHAR(100), 
    @Spouse NVARCHAR(100), 
    @Marital NVARCHAR(50), 
    @Nat NVARCHAR(50), 
    @Rel NVARCHAR(50), 
    @ResStatus NVARCHAR(50), 
    @PlaceOfBirth NVARCHAR(100), 
    @CountryOfBirth NVARCHAR(100), 
    @Street NVARCHAR(250), 
    @Locality NVARCHAR(150), 
    @Town NVARCHAR(150), 
    @PO NVARCHAR(100), 
    @City NVARCHAR(100), 
    @State NVARCHAR(100), 
    @Country NVARCHAR(100), 
    @Pin NVARCHAR(10), 
    @AddrType NVARCHAR(50), 
    @IsSame NVARCHAR(5), 
    @PermAddr NVARCHAR(500), 
    @Occ NVARCHAR(50), 
    @EmpName NVARCHAR(150), 
    @BusNature NVARCHAR(150), 
    @Role NVARCHAR(100), 
    @Income NVARCHAR(100), 
    @Funds NVARCHAR(100), 
    @PAN NVARCHAR(20), 
    @PANName NVARCHAR(100), 
    @DLNum NVARCHAR(30), 
    @DLDOB DATE, 
    @DLName NVARCHAR(100), 
    @AadhaarPath NVARCHAR(500), 
    @PANPath NVARCHAR(500), 
    @DLPath NVARCHAR(500), 
    @AddrPath NVARCHAR(500), 
    @SignPath NVARCHAR(500) 
AS 
BEGIN 
    SET NOCOUNT ON; 
    UPDATE [dbo].[KYCDetails] SET 
        [AccountType] = @AcType, 
        [CustomerType] = @CustType, 
        [PreferredBranch] = @Branch, 
        [Email] = @Email, 
        [EmailOTP] = @EmailOTP, 
        [MobileNumber] = @Mobile, 
        [AlternateMobileNumber] = @AltMobile, 
        [AadhaarMobileOTP] = @AadhaarMobileOTP, 
        [AadhaarNumber] = @AadhaarNum, 
        [AadhaarOTP] = @AadhaarOTP, 
        [AadhaarName] = @AadhaarName, 
        [AadhaarDOB] = @AadhaarDOB, 
        [Gender] = @Gender, 
        [FullLegalName] = @FullName, 
        [FatherName] = @FatherName, 
        [MotherName] = @MotherName, 
        [SpouseGuardianName] = @Spouse, 
        [MaritalStatus] = @Marital, 
        [Nationality] = @Nat, 
        [Religion] = @Rel, 
        [ResidentialStatus] = @ResStatus, 
        [PlaceOfBirth] = @PlaceOfBirth, 
        [CountryOfBirth] = @CountryOfBirth, 
        [StreetHouseLandmark] = @Street, 
        [AreaLocality] = @Locality, 
        [LocationVillageTown] = @Town, 
        [PostOffice] = @PO, 
        [CityDistrict] = @City, 
        [State] = @State, 
        [Country] = @Country, 
        [Pincode] = @Pin, 
        [TypeOfAddress] = @AddrType, 
        [IsPermanentAddressSame] = @IsSame, 
        [PermanentAddress] = @PermAddr, 
        [OccupationType] = @Occ, 
        [EmployerName] = @EmpName, 
        [NatureOfBusiness] = @BusNature, 
        [Designation] = @Role, 
        [AnnualIncomeRange] = @Income, 
        [SourceOfFunds] = @Funds, 
        [PANNumber] = @PAN, 
        [PANHolderName] = @PANName, 
        [DrivingLicenceNumber] = @DLNum, 
        [DrivingLicenceDOB] = @DLDOB, 
        [DrivingLicenceName] = @DLName, 
        [AadhaarCardPath] = @AadhaarPath, 
        [PANCardPath] = @PANPath, 
        [PassportDLPath] = @DLPath, 
        [AddressProofPath] = @AddrPath, 
        [SignatureScanPath] = @SignPath 
    WHERE [Id] = @Id; 
END
