IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KYCDetails]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[KYCDetails] (
        [Id] INT IDENTITY(1,1) PRIMARY KEY, 
        [AccountType] NVARCHAR(50) NOT NULL, 
        [CustomerType] NVARCHAR(50) NOT NULL, 
        [PreferredBranch] NVARCHAR(100) NOT NULL, 
        [ApplicationDate] DATE NOT NULL, 
        [Email] NVARCHAR(150) NOT NULL, 
        [EmailOTP] NVARCHAR(10) NOT NULL, 
        [MobileNumber] NVARCHAR(15) NOT NULL, 
        [AlternateMobileNumber] NVARCHAR(15) NULL, 
        [AadhaarMobileOTP] NVARCHAR(10) NOT NULL, 
        [AadhaarNumber] NVARCHAR(20) NOT NULL CONSTRAINT UQ_Aadhaar UNIQUE, 
        [AadhaarOTP] NVARCHAR(10) NOT NULL, 
        [AadhaarName] NVARCHAR(100) NOT NULL, 
        [AadhaarDOB] DATE NOT NULL, 
        [Gender] NVARCHAR(20) NOT NULL, 
        [FullLegalName] NVARCHAR(100) NOT NULL, 
        [FatherName] NVARCHAR(100) NOT NULL, 
        [MotherName] NVARCHAR(100) NOT NULL, 
        [SpouseGuardianName] NVARCHAR(100) NOT NULL, 
        [MaritalStatus] NVARCHAR(50) NOT NULL, 
        [Nationality] NVARCHAR(50) NOT NULL, 
        [Religion] NVARCHAR(50) NULL, 
        [ResidentialStatus] NVARCHAR(50) NOT NULL, 
        [PlaceOfBirth] NVARCHAR(100) NULL, 
        [CountryOfBirth] NVARCHAR(100) NULL, 
        [StreetHouseLandmark] NVARCHAR(250) NOT NULL, 
        [AreaLocality] NVARCHAR(150) NOT NULL, 
        [LocationVillageTown] NVARCHAR(150) NOT NULL, 
        [PostOffice] NVARCHAR(100) NOT NULL, 
        [CityDistrict] NVARCHAR(100) NOT NULL, 
        [State] NVARCHAR(100) NOT NULL, 
        [Country] NVARCHAR(100) NOT NULL, 
        [Pincode] NVARCHAR(10) NOT NULL, 
        [TypeOfAddress] NVARCHAR(50) NOT NULL, 
        [IsPermanentAddressSame] NVARCHAR(5) NOT NULL, 
        [PermanentAddress] NVARCHAR(500) NULL, 
        [OccupationType] NVARCHAR(50) NOT NULL, 
        [EmployerName] NVARCHAR(150) NULL, 
        [NatureOfBusiness] NVARCHAR(150) NULL, 
        [Designation] NVARCHAR(100) NULL, 
        [AnnualIncomeRange] NVARCHAR(100) NOT NULL, 
        [SourceOfFunds] NVARCHAR(100) NOT NULL, 
        [PANNumber] NVARCHAR(20) NOT NULL CONSTRAINT UQ_PAN UNIQUE, 
        [PANHolderName] NVARCHAR(100) NOT NULL, 
        [DrivingLicenceNumber] NVARCHAR(30) NULL, 
        [DrivingLicenceDOB] DATE NULL, 
        [DrivingLicenceName] NVARCHAR(100) NULL, 
        [AadhaarCardPath] NVARCHAR(500) NOT NULL, 
        [PANCardPath] NVARCHAR(500) NOT NULL, 
        [PassportDLPath] NVARCHAR(500) NULL, 
        [AddressProofPath] NVARCHAR(500) NULL, 
        [SignatureScanPath] NVARCHAR(500) NOT NULL, 
        [CreatedAt] DATETIME DEFAULT GETDATE(), 
        [VerificationStatus] NVARCHAR(20) DEFAULT 'Pending' NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[KYCDetails]') AND name = 'VerificationStatus')
BEGIN
    ALTER TABLE [dbo].[KYCDetails] ADD [VerificationStatus] NVARCHAR(20) DEFAULT 'Pending' NOT NULL;
END
